//
//  GSCoreDataObject+NonAutoGenerated.h
//  GarageStorage
//
//  Created by Sam Voigt on 4/28/15.
//  Copyright (c) 2015 Wellframe. All rights reserved.
//

#import "GSCoreDataObject.h"

extern NSString *const kGSTypeKey;
extern NSString *const kGSIdentifierKey;
extern NSString *const kGSSyncStatusKey;

@interface GSCoreDataObject (NonAutoGenerated)

@end
