//
//  GSCoreDataObject+NonAutoGenerated.m
//  GarageStorage
//
//  Created by Sam Voigt on 4/28/15.
//  Copyright (c) 2015 Wellframe. All rights reserved.
//

#import "GSCoreDataObject+NonAutoGenerated.h"

NSString *const kGSTypeKey = @"gs_type";
NSString *const kGSIdentifierKey = @"gs_identifier";
NSString *const kGSSyncStatusKey = @"gs_syncStatus";

@implementation GSCoreDataObject (NonAutoGenerated)

@end
